const webpush=require("web-push");
const db=require("./db");
const {analyzeMarket}=require("./signal");
const TF_NAME={"60":"1시간","240":"4시간","day":"일봉"};
function pushConfigured(){return Boolean(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT)}
function setupWebPush(){if(!pushConfigured())return false;webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);return true}
async function subscriptionsForDevice(deviceId){return await db.select("push_subscriptions",{select:"id,device_id,endpoint,p256dh,auth",device_id:`eq.${deviceId}`})||[]}
async function sendToDevice(deviceId,payload){if(!setupWebPush())return{sent:0,failed:0,setupRequired:true};const subs=await subscriptionsForDevice(deviceId);let sent=0,failed=0;for(const s of subs){try{await webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},JSON.stringify(payload),{TTL:3600,urgency:"high"});sent++}catch(e){failed++;const code=e?.statusCode||e?.status;if(code===404||code===410){try{await db.remove("push_subscriptions",{id:`eq.${s.id}`})}catch{}}}}return{sent,failed,setupRequired:false}}
function ruleMatches(rule,s){if(!s)return false;if(s.score<Number(rule.min_score||0))return false;if(s.quality<Number(rule.min_quality||0))return false;if(s.adx<Number(rule.min_adx||0))return false;if(s.volRatio<Number(rule.min_vol_ratio||0))return false;if(rule.require_regime&&rule.require_regime!=="ANY"&&s.regime!==rule.require_regime)return false;return true}
function cooldownPassed(rule){if(!rule.last_triggered_at)return true;return Date.now()-new Date(rule.last_triggered_at).getTime()>=Math.max(1,Number(rule.cooldown_minutes||240))*60000}
async function loadRules(deviceId){const q={select:"*",enabled:"eq.true",order:"created_at.asc"};if(deviceId)q.device_id=`eq.${deviceId}`;return await db.select("alert_rules",q)||[]}
async function evaluateRules({deviceId=null,sendPush=true}={}){const rules=await loadRules(deviceId);if(!rules.length)return{rules:0,evaluated:0,triggered:0,pushSent:0,results:[]};const markets=[...new Set(rules.map(r=>r.market))],analyses={};for(let i=0;i<markets.length;i++){analyses[markets[i]]=await analyzeMarket(markets[i]);if(i<markets.length-1)await new Promise(r=>setTimeout(r,400))}let triggered=0,pushSent=0,evaluated=0;const results=[];for(const rule of rules){evaluated++;const s=analyses[rule.market]?.[rule.tf],match=ruleMatches(rule,s),cooldown=cooldownPassed(rule),item={ruleId:rule.id,market:rule.market,tf:rule.tf,match,cooldown,signal:s||null,triggered:false};if(match&&cooldown){triggered++;item.triggered=true;const title=`${rule.market} ${TF_NAME[rule.tf]||rule.tf} Signal`,body=`Score ${s.score>=0?"+":""}${s.score} · Quality ${s.quality}/100 · ADX ${s.adx.toFixed(1)} · ${s.regime}`,payload={title,body,url:"/",market:rule.market,tf:rule.tf,score:s.score,quality:s.quality,price:s.price};let push={sent:0,failed:0};if(sendPush)push=await sendToDevice(rule.device_id,payload);pushSent+=push.sent||0;const now=new Date().toISOString();await db.update("alert_rules",{id:`eq.${rule.id}`},{last_triggered_at:now});await db.insert("signal_events",{device_id:rule.device_id,rule_id:rule.id,market:rule.market,tf:rule.tf,score:s.score,quality:s.quality,adx:s.adx,vol_ratio:s.volRatio,regime:s.regime,price:s.price,signal_candle_time:s.candleTime,push_sent:(push.sent||0)>0,payload});item.push=push}results.push(item)}return{rules:rules.length,evaluated,triggered,pushSent,results}}
module.exports={pushConfigured,sendToDevice,evaluateRules};
